# Generated by Django 4.0.6 on 2022-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='chief',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
